name: Setup environment
description: Setup environment for Node.js project

inputs:
  npm-token:
    description: NPM token
    required: true
  github-workspace:
    description: Github workspace
    required: true

runs:
  using: composite
  steps:

    # Install Node.js
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/:_authToken=${{ inputs.npm-token  }}

    # Create .npmrc
    - name: Create .npmrc
      run: |
        echo 'registry=https://registry.npmjs.org/' >> ${{ inputs.github-workspace }}/.npmrc
        echo 'always-auth=true' >> ${{ inputs.github-workspace }}/.npmrc 
        echo 'https://registry.npmjs.org/:_authToken=${{ inputs.npm-token  }}' >> ${{ inputs.github-workspace }}/.npmrc
      shell: bash

    # Install your dependencies
    - run: npm ci
      shell: bash
