name: Publish new package version

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

        # Setup environment
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-workspace: ${{ github.workspace }}

      #Create build and publish new version
      - run: |
          git config --global user.email "yashchuk19993@gmail.com"
          git config --global user.name "Andrii Yashchuk"
          npm run build
          npm run publish
